### ISSUE TITLE
Where can I find the testing dataset for Chapter4_StructureFromMotion?

### ISSUE THREAD

**Issue by jiapei100** [MasteringOpenCV/code#10]
To whom it may concern:

Is there a testing dataset containing multiple images that are suitable for Chapter4_StructureFromMotion ?

Cheers
Pei

**Comment by rebelmachina** [comment]
There's no public access to any of the links above.

**Comment by HelliceSaouli** [comment]
any way to get the data ?

**Comment by rebelmachina** [comment]
Try these: http://cvlab.epfl.ch/data/strechamvs, the fountain dataset is missing but the alternatives there are suitable for MVG too.
