### ISSUE TITLE
Chapter 3: Markless AR, unexpected behaviour

### ISSUE THREAD

**Issue by oliw** [MasteringOpenCV/code#11]
Hi,
Have built the application on latest Ubuntu with OpenCV 2.4.5 and am getting unexpected results.

See youtube screencast here: http://www.youtube.com/watch?v=aTwJZmLft8w

Any ideas what is causing this? Could it be to do with my webcam?

It always eventually just crashes with 'The program has unexpectedly finished.'

**Comment by kghalieh** [comment]
thanks or your code!
I cant understand the N's
I think that N1 and N2 limites the scaling between 0.1 and 4 but what about px,py what is the theroy behind it
