### ISSUE TITLE
How to build my own OpenCV package under Ubuntu 14.04 ?

### ISSUE THREAD

**Issue by ghost** [MasteringOpenCV/code#47]
I installed OpenCV following this official documentation. Everything is fine. However, when I set the flag of a window to use OpenGL, I get this error:

    OpenCV Error: No OpenGL support (Library was built without OpenGL support) in CvWindow

The solution is to build my own OpenCV package as stated:

> The precompiled OpenCV you can download from opencv.org build without
> OpenGL support. In order to run this sample you may want to build your
> own OpenCV package.

The problem is that the official documentation shows how to built my own OpenCV package under Windows. How to do the same thing on Ubuntu 14.04  to use it from Python ?

Thank you in advance for any helpful hints.
BEGUERADJ.

**Comment by aleksandaratanasov** [comment]
What "own package" means is just to build OpenCV from source and use it in your projects. Ubuntu along with Debian and many others have OpenCV in the official repositories however the build of the library is very limited when it comes to extra features including OpenGL, Qt etc. I'm almost certain that even if installed from the repositories OpenCV's package comes with Python support. You can easily make sure it is so when you configure your OpenCV build (using cmake) and enable it.

**Comment by shervinemami** [comment]
Closing this bug.
