### ISSUE TITLE
OpenCV: libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by begueradj** [MasteringOpenCV/code#48]
I installed OpenCV correctly on Ubuntu 14.04. However, when I run: `import cv2` I get this error message: 

    >>> import cv2
    libdc1394 error: Failed to initialize libdc1394
I read the answers fro a similar question, but all of them assume the existence of this file which I don't have: `/dev/raw1394`. So I installed the library:

    sudo apt-get install libdc1394-22-dev libdc1394-22 libdc1394-utils

But still get the same error.

Note that this [answer][3] is the only one that works for me, however I can not pick it because I need to use camera in my application.

How can I resolve this ?

Thank you in advance.
Begueradj

  [1]: http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394
  [2]: http://www.linuxforums.org/forum/ubuntu-linux/171972-libdc1394-error.html
  [3]: http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394/26028597#26028597

**Comment by shervinemami** [comment]
Hi Begueradj,

This is the bug section for the book rather than for OpenCV in general. So I think you should search the web about firewire cameras in OpenCV using python and if you don't find the answer then ask on "answers.opencv.org".

Cheers,
Shervin.

**Comment by begueradj** [comment]
@shervinemami  I'm very sorry, I did not even know I was posting after a book. Sorry, I'm not familiar with this website yet. You can remove my question.
