### ISSUE TITLE
Chapter 6 issues

### ISSUE THREAD

**Issue by akapusta** [MasteringOpenCV/code#49]
There are a few problems with the code for Chapter 6. The readme says --help returns some helpful information, but it is not recognized. 
All of the commands apparently need additional inputs which are not clearly described and are not provided as an example. It is unclear what is needed in annotation files, shape models, detector files, etc. I assume some of these can be created with the training executables, but there is no information or examples of the files or how to run the executables, or their outputs.
Can more code/example files be provided or more information be added to the readme?

**Comment by shervinemami** [comment]
Hi Akapusta, the info is described in Chapter 6 of the book. But anyway, the author of Chapter 6 (Jason Saragih) has posted a new mini-tutorial, that I've added to the bottom of the README file of Ch6.
