### ISSUE TITLE
Chapter3 MarkerlessAR

### ISSUE THREAD

**Issue by moreli** [MasteringOpenCV/code#8]
I'm trying to run this on Mac (Mountain Lion) with OpenCV 2.4.5
I'm getting the following error:

``` terminal
OpenCV Error: No OpenGL support (Library was built without OpenGL support) in CvWindow
```

When trying to build with OpenGL the option does not show up in cmake. The latest is configured not to have openGL (CMakeLists.txt line 131)

``` terminal
OCV_OPTION(WITH_OPENGL         "Include OpenGL support"                      OFF  IF (NOT ANDROID AND NOT APPLE) )
```

I've even tried to brew OpenCV with the QT option, but I get the same error still.
How can I run this on mac, if I can't compile it with OpenGL?

**Comment by begueradj** [comment]
Hi,
How to built my own OpenCV package in Ubuntu 14.04 to use along with Python ? The  official documentation deals only with Windows.

**Comment by BENMFeng** [comment]
@begueradj, I just succeed in building OpenCV 3.0 beta in Ubuntu 14.04 (VM on win7) with Python support, maybe you can follow my procedure:
<pre><code class="markdown">#Begin
#update your deb source and install build-essential 
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install libevent-dev python-dev
#install python essential library
sudo apt-get install python-setuptools python-pip
sudo apt-get install python-numpy python-scipy
sudo apt-get install python-matplotlib
#install Qt 5.0, not necessary 
wget http://mirror.bit.edu.cn/qtproject/archive/qt/5.0/5.0.2/qt-linux-opensource-5.0.2-x86_64-offline.run
chmod +x qt-linux-opensource-5.0.2-x86_64-offline.run
./qt-linux-opensource-5.0.2-x86_64-offline.run
sudo apt-get install mesa-common-dev
sudo apt-get install libglu1-mesa-dev -y
#install opencv required lib
sudo apt-get -y install build-essential cmake pkg-config
sudo apt-get -y install libjpeg62-dev
sudo apt-get -y install libtiff4-dev libjasper-dev
sudo apt-get -y install libgtk2.0-dev
sudo apt-get -y install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get -y install libdc1394-22-dev
sudo apt-get -y install libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
sudo apt-get -y install libtbb-dev
sudo apt-get -y install libqt4-dev
sudo apt-get -y install libopencv-dev --fix-missing
#build & install opencv 3.0.0 beta
wget https://github.com/Itseez/opencv/archive/3.0.0-beta.zip
unzip opencv-3.0.0-beta.zip
cd opencv-3.0.0-beta/
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON \
-D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON \
-D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
make
sudo make install
#End 
</code></pre>

**Comment by begueradj** [comment]
@BENMFeng  Thank you VERY much. I will follow your instructins in few minutes by now. However, it is said that OpenCV3.0 is not stable, so may be it is better to avoid using it for a serious project development ?

**Comment by BENMFeng** [comment]
@begueradj , I think it is OK, but for security, you can install 2.4.11 or 2.4.10.

**Comment by begueradj** [comment]
@BENMFeng your solution works perfectly fine. In fact I asked this in a separate question almost the same time as I commented here. So may be it is better you post your comment as an answer and mark my question as solved. Thank you again.
