### ISSUE TITLE
Chapter8_FaceRecognition

### ISSUE THREAD

**Issue by danielpanda** [MasteringOpenCV/code#86]
```
CMake Warning at C:/OpenCV/build/OpenCVConfig.cmake:161 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:15 (FIND_PACKAGE)


CMake Error at CMakeLists.txt:15 (FIND_PACKAGE):
  Found package configuration file:

    C:/OpenCV/build/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


-- Configuring incomplete, errors occurred!
See also "C:/MasteringOpenCV/Chapter8_FaceRecognition/build/CMakeFiles/CMakeOutp
ut.log".

```

I've this error, what a solution for this @_@

**Comment by shervinemami** [comment]
Hi, you need to fix your OpenCV and/or Cmake installation. I'm guessing you
have installed OpenCV binaries for the wrong compiler or the wrong
32-bit/64-bit size.

Cheers,
Shervin Emami.

**Comment by danielpanda** [comment]
Hi, Sir @shervinemami .
I have installed the OpenCV 2.4.9. in the opencv.org it just have that. 2.4.1 is gone.
how to fix that OpenCV Binaries. Thank You Sir.
Sorry for disturbing you, i have a assignment from my college.

Thanks

**Comment by danielpanda** [comment]
@shervinemami 
i've successed to build in my command prompt. but no file WebcamFaceRec.sln  @_@

Cheers

**Comment by danielpanda** [comment]
[
![image](https://user-images.githubusercontent.com/29721735/28210381-4c681212-68c1-11e7-835e-9b613d8dbe63.png)
](url)

sir @shervinemami @dannyxyz22  @royshil @SSteve @BloodAxe , can you help me with this?? please. Thankyou so much.

Cheers.

**Comment by BloodAxe** [comment]
You should start executable target instead ALL_BUILD. The ALL_BUILD target is cmake-specific task that builds all projects in a solution. Instead you want to select the main project and run it. Please referer to documentation of your IDE.

**Comment by danielpanda** [comment]
[
![image](https://user-images.githubusercontent.com/29721735/28220474-c7b0c43c-68e9-11e7-8871-8f8dae53694b.png)
](url)
[
![image](https://user-images.githubusercontent.com/29721735/28220517-f847401c-68e9-11e7-9a83-a71facbd9765.png)
](url)
now the system can't start because opencv_objdetect2411.dll , opencv_imgproc2411.dll

and

why this error again to me? [
![image](https://user-images.githubusercontent.com/29721735/28220544-1acd04a0-68ea-11e7-8d6d-8bb595cd7003.png)
](url)

@BloodAxe @shervinemami @dannyxyz22 @royshil @SSteve 
Thankyou very much, please help me in this case.
Cheers.

**Comment by BloodAxe** [comment]
If you were building OpenCV as shared library, that you need to copy dll files new to your executable. Or you should re-build OpenCV as static libraries. Please, spend some time on reading more what is the difference between static vs shared libraries. I'm going to close this issue as it's not related to chapter's code.
