### ISSUE TITLE
Error when running chapter 5 code - ANPR

### ISSUE THREAD

**Issue by chinthakawk** [MasteringOpenCV/code#9]
I was able to successfully build the code in Windows 8 with OpenCV 2.4.5. But when I run the ANPR.exe following error returned. What may be the reason. Thank you.

OpenCV Error: Bad argument (train data must be floating-point matrix) in cvCheck
TrainData, file ......\src\opencv\modules\ml\src\inner_functions.cpp, line 857

**Comment by geniusunil** [comment]
Where would i find the files OCR.xml and SVM.xml?
