### ISSUE TITLE
'cstddef' file not found

### ISSUE THREAD

**Issue by NiteshGarg2107** [MasteringOpenCV/code#93]
In Chapter 2 I got this error (**'cstddef' file not found**) when I tried to import this code in my code with Swift and xcode9 so please let meknow how  can I resolve this issue.
Thanks

**Comment by BloodAxe** [comment]
This code is written for Objective-C language. We do not support Swift. However, you can wrap this code in ObjC to Swig binding. There are plenty of information how to do it over the Internet.
